### ISSUE TITLE
关于作者可能出于主观原因或输入法问题导致的别字更正issue

### ISSUE THREAD

**Issue by HoYuenhang** [tonyleelyy/LiveOCR#1]
怀疑出现问题处：
> 花了1天+1个网上写出来这个项目。

请求更正为以下内容：
花了1天+1个晚上写出来这个项目。

お願いいたします。

**Comment by tonyleelyy** [comment]
> 怀疑出现问题处：
> 
> > 花了1天+1个网上写出来这个项目。
> 
> 请求更正为以下内容：
> 花了1天+1个晚上写出来这个项目。
> 
> お願いいたします。

您就是列文虎克？🤣
